name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -name: Build the Docker image
     uses: actions/checkout@v4
    

    -name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v1

    -name: Build Docker image
     run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/Projet_Devops:${{ github.sha }}

    -name: Log into DockerHub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

    -name: Tag Docker inamge as latest
     run: | 
      docker tag ${{ secrets.DOCKER_USERNAME }}/Projet_Devops:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/Projet_Devops:latest

    -name: Push Docker image
     run: |
      docker push ${{ secrets.DOCKER_USERNAME }}/Projet_Devops:${{ github.sha }}
      docker push ${{ secrets.DOCKER_USERNAME }}/Projet_Devops:latest

    
